/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package manager;

import com.mycompany.restaurant.UserMainFrame;
import java.awt.Color;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author tanysha
 */
public class CategoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoryPanel
     */
    
    String[] items;
    String path=System.getProperty("user.dir");
    private static CategoryPanel reference;
    //private static final Object[][] rowData = {{1, "pizza", "chese", 100}};
    private static final Object[] columnNames = { "Id","Name", "Discription", "Price"};
    Object[][] dishes ;
    Vector<Object> dish = new Vector<Object>();
   private DefaultTableModel model;
    
    
   private CategoryPanel() {
       model = new DefaultTableModel(null, columnNames);
         try {
         items = Manager.getThread().getAllCategories(); 
        
         
         }
          catch (IOException ex) {
            Logger.getLogger(CategoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setBackground(Color.getHSBColor(276,9,95));
        addCategory.setText("  Add category");
        deleteCategory.setText("  Delete category");
        //menu.setModel();
                   // model.addRow(r1);
     
        
    }
     public static CategoryPanel getReference(){
         if (reference==null){
             reference = new CategoryPanel();
         }
         return reference;
     }
     
     public JComboBox getCategory(){
         return category;
     }
     public void setTextOfLable(String newText ){
     nameOfcategory.setText( newText);
     }
     
     public void addNewRow(Vector<Object> newDish){
         model.addRow(newDish);
     }
     public String getSelectCategory(){
          return category.getSelectedItem().toString();
     }
     public void addCategoryItem(String name){
         category.addItem(name);
     }
     public void deleteCategoryItem(String name){
         category.removeItem(name);
     }
     public String[] getItemsOfCategory(){
         return items;
     }
     public void nameOfCategory(){
         nameOfcategory.setText(category.getSelectedItem().toString());
     }
     public boolean isCategory(String name){
       int i=0;
       while(i<category.getItemCount()){
           if(category.getItemAt(i) == null ? name == null : category.getItemAt(i).equals(name)) {
               return true;
           } 
           i++;
       }
       return false;
    }
     public void setModelData( Object[][] selectDishes){
          model.setDataVector(selectDishes, columnNames);
     }
     public void writingData(){
         
        model.setDataVector(null, columnNames);
      try {
          int i=0; 
          dishes=new Object[Manager.getThread().getFood(category.getSelectedItem().toString()).toArray().length][4];
          while(i<Manager.getThread().getFood(category.getSelectedItem().toString()).toArray().length){
               
               //dish.removeAllElements();
              
               dishes[i][0]= Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getId();
               dishes[i][1]=Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getName();
               dishes[i][2]= Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getCompound();
               dishes[i][3]= Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getPrice(); 
               
              
               i++;
               
          }
          
          
         }
          catch (IOException ex) {
            Logger.getLogger(CategoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setDataVector(dishes, columnNames);
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        category = new javax.swing.JComboBox(items);
        addCategory = new javax.swing.JButton();
        nameOfcategory = new javax.swing.JLabel();
        search_dish = new javax.swing.JButton();
        add_dish = new javax.swing.JButton();
        delete_dish = new javax.swing.JButton();
        deleteCategory = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        menu = new javax.swing.JTable();

        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });

        addCategory.setIcon(new javax.swing.ImageIcon(path+"\\src\\main\\java\\manager\\image\\add.png"));
        addCategory.setText("Add category");
        addCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryActionPerformed(evt);
            }
        });

        nameOfcategory.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        nameOfcategory.setForeground(new java.awt.Color(0, 0, 51));
        nameOfcategory.setText("Name of category");

        search_dish.setBackground(new java.awt.Color(204, 255, 204));
        search_dish.setText("search");
        search_dish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_dishActionPerformed(evt);
            }
        });

        add_dish.setBackground(new java.awt.Color(204, 204, 255));
        add_dish.setText("add");
        add_dish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_dishActionPerformed(evt);
            }
        });

        delete_dish.setBackground(new java.awt.Color(255, 204, 204));
        delete_dish.setText("delete");
        delete_dish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_dishActionPerformed(evt);
            }
        });

        deleteCategory.setIcon(new javax.swing.ImageIcon(path+"\\src\\main\\java\\manager\\image\\delete16.png"));
        deleteCategory.setText("Delete category");
        deleteCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCategoryActionPerformed(evt);
            }
        });

        menu.setModel(model);
        jScrollPane1.setViewportView(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nameOfcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(deleteCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(category, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_dish, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(search_dish, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(delete_dish, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nameOfcategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(addCategory)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCategory)
                        .addGap(54, 54, 54)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_dish)
                    .addComponent(search_dish)
                    .addComponent(delete_dish))
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryActionPerformed
        // TODO add your handling code here:
        new AddCategoryFrame().setVisible(true);
    }//GEN-LAST:event_addCategoryActionPerformed

    private void add_dishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_dishActionPerformed
        // TODO add your handling code here:
        new AddDishFrame().setVisible(true);
    }//GEN-LAST:event_add_dishActionPerformed

    private void deleteCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCategoryActionPerformed
        // TODO add your handling code here:
        new DeleteCategoryFrame().setVisible(true);
    }//GEN-LAST:event_deleteCategoryActionPerformed

    private void delete_dishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_dishActionPerformed
        // TODO add your handling code here:
        new DeleteDishFrame().setVisible(true);
    }//GEN-LAST:event_delete_dishActionPerformed

    private void search_dishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_dishActionPerformed
        // TODO add your handling code here:
        new SearchDishFrame().setVisible(true);
    }//GEN-LAST:event_search_dishActionPerformed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
       int l =0;
        nameOfcategory.setText(category.getSelectedItem().toString());
        model.setDataVector(null, columnNames);
      try {
          int i=0; int j=0;
          l=Manager.getThread().getFood(category.getSelectedItem().toString()).toArray().length;
          dishes=new Object[Manager.getThread().getFood(category.getSelectedItem().toString()).toArray().length][4];
          while(i<Manager.getThread().getFood(category.getSelectedItem().toString()).toArray().length){
               
               //dish.removeAllElements();
              
               dishes[i][0]= Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getId();
               dishes[i][1]= Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getName();
               dishes[i][2]= Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getCompound();
               dishes[i][3]= Manager.getThread().getFood(category.getSelectedItem().toString()).get(i).getPrice(); 
               
              
               i++;
               
          }
          
          
         }
          catch (IOException ex) {
            Logger.getLogger(CategoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setDataVector(dishes, columnNames);
        for (int i=0; i<l; i++){
            for (int j=0; j<4; j++)         // зверніть увагу на відсутність фігурної дужки
                 System.out.print (dishes[i][j]+"    ");//даний рядок відноситься до масиву по j
            System.out.println ();          //виводимо символи переводу каретки і нового рядка
                                            //після кожного проходження стовпцевих елементів рядка
        }
    }//GEN-LAST:event_categoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategory;
    private javax.swing.JButton add_dish;
    private javax.swing.JComboBox category;
    private javax.swing.JButton deleteCategory;
    private javax.swing.JButton delete_dish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable menu;
    private javax.swing.JLabel nameOfcategory;
    private javax.swing.JButton search_dish;
    // End of variables declaration//GEN-END:variables
}
