/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package manager;

import java.awt.Color;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tanysha
 */
public class PersonnelPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonnelPanel
     */
    private static final Object[] columnNames = { "Id","Name", "Surname", "Salary"};
    private DefaultTableModel model;
    Object[][] personal ;
    private static PersonnelPanel reference;
    
    private PersonnelPanel() {
        model = new DefaultTableModel(null, columnNames);
        
        initComponents();
        setBackground(Color.getHSBColor(276,9,95));
        writingData();
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add_person = new javax.swing.JButton();
        search_person = new javax.swing.JButton();
        delete_person = new javax.swing.JButton();
        actoinWithP = new javax.swing.JLabel();
        all = new javax.swing.JButton();

        jTable1.setModel(model);
        jScrollPane1.setViewportView(jTable1);

        add_person.setBackground(new java.awt.Color(204, 204, 255));
        add_person.setText("add");
        add_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_personActionPerformed(evt);
            }
        });

        search_person.setBackground(new java.awt.Color(204, 255, 204));
        search_person.setText("search");
        search_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_personActionPerformed(evt);
            }
        });

        delete_person.setBackground(new java.awt.Color(255, 204, 204));
        delete_person.setText("delete");
        delete_person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_personActionPerformed(evt);
            }
        });

        actoinWithP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        actoinWithP.setText("Personnel");

        all.setBackground(new java.awt.Color(255, 255, 153));
        all.setText("all");
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actoinWithP)
                .addGap(332, 332, 332))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(add_person, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(search_person, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(delete_person, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(all, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(actoinWithP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_person)
                    .addComponent(search_person)
                    .addComponent(delete_person)
                    .addComponent(all))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents
   public static PersonnelPanel getReference(){
         if (reference==null){
             reference = new PersonnelPanel();
         }
         return reference;
     }
   public void setTextOfLable(String newText){
       actoinWithP.setText(newText);
   }
   public void setModelData(Object[][] newData){
       model.setDataVector(newData, columnNames);
   }
   public void writingData (){
       model.setDataVector(null, columnNames);
       try {
          int i=0; 
          //Manager.getThread().addEmployee(999678687, "terte","sfsdf", 55);
          System.out.print(Manager.getThread().getEmployees().toArray().length);
          personal=new Object[Manager.getThread().getEmployees().toArray().length][4];
          while(i<Manager.getThread().getEmployees().toArray().length){
               
               //dish.removeAllElements();
              
               personal[i][0]= Manager.getThread().getEmployees().get(i).getId();
               personal[i][1]=Manager.getThread().getEmployees().get(i).getName();
               personal[i][2]= Manager.getThread().getEmployees().get(i).getSurname();
               personal[i][3]= Manager.getThread().getEmployees().get(i).getSalary(); 
               
              
               i++;
               
          }
           
         
         }
          catch (IOException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setDataVector(personal, columnNames);
          
   }
    public void addNewRow(Vector<Object> newPersonnel){
         model.addRow(newPersonnel);
     }
    private void delete_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_personActionPerformed
        // TODO add your handling code here:
        new DeletePersFrame().setVisible(true);
    }//GEN-LAST:event_delete_personActionPerformed

    private void add_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_personActionPerformed
        // TODO add your handling code here:
        new AddPersonnelFrame().setVisible(true);
    }//GEN-LAST:event_add_personActionPerformed

    private void search_personActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_personActionPerformed
        // TODO add your handling code here:
        
        new SearchPersFrame().setVisible(true);
    }//GEN-LAST:event_search_personActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
        // TODO add your handling code here:
        actoinWithP.setText("Personnel");
        writingData ();
    }//GEN-LAST:event_allActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actoinWithP;
    private javax.swing.JButton add_person;
    private javax.swing.JButton all;
    private javax.swing.JButton delete_person;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search_person;
    // End of variables declaration//GEN-END:variables
}
